apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: sample
spec:
  type: NodePort
  selector:
    app: sample
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
